flocking:
  ros__parameters:
    wheel_turning:
      hard_turn_on_angle_threshold: 90.0   # in degrees, threshold to trigger a hard turn
      soft_turn_on_angle_threshold: 70.0  # in degrees, threshold to switch to soft turning
      no_turn_angle_threshold: 10.0        # in degrees ians, threshold below which no turning is needed
      max_speed: 10.0                      # maximum wheel speed
    flocking:
      target_distance: 0.75                # preferred distance between robots
      gain: 1000.0                         # gain for the Lennard-Jones potential
      exponent: 2.0                        # exponent for the Lennard-Jones potential
    wheel_separation: 0.160                 # distance between wheels for differential drive kinematics
    wheel_radius: 0.033                     # radius of the wheels
    goal.x: 0.0                             # goal position x-coordinate in metres
    goal.y: 10.0                            # goal position y-coordinate in metres
    goal.gain: 1000.0                       # attraction gain toward the goal
